package com.duoshield.app.call;

import android.content.Context;
import android.content.SharedPreferences;
import android.util.Log;

import androidx.security.crypto.EncryptedSharedPreferences;
import androidx.security.crypto.MasterKey;

/**
 * Thread-safe cache for Cloudflare TURN credentials with optional
 * {@link EncryptedSharedPreferences} persistence.
 *
 * <h3>Why persistence matters</h3>
 * The previous implementation was in-memory only.  When the OS kills the app
 * process (OOM, force-quit, device restart) and the user taps an incoming-call
 * notification immediately, the cache is cold.  {@link CallManager#buildIceServers}
 * runs before the async {@link TurnCredentialFetcher#prefetch} finishes, so the
 * call starts STUN-only.  On CGNAT mobile networks this causes a silent failure.
 *
 * <p>Persisting credentials (TTL 1 hour, same as the Cloudflare expiry window)
 * means the cache is warm on first access even after a process kill, eliminating
 * the race.
 *
 * <h3>Lifecycle</h3>
 * <ol>
 *   <li>Call {@link #init(Context)} once early in {@code CallActivity.onCreate()}
 *       before {@link TurnCredentialFetcher#prefetch}.  This loads any persisted
 *       credentials from disk into memory in one synchronised call.</li>
 *   <li>{@link TurnCredentialFetcher} calls {@link #get()} (no-arg) to write fresh
 *       credentials.  If the prefs store was already initialised, the new values are
 *       persisted automatically.</li>
 *   <li>{@link CallManager} calls {@link #get()} to read credentials.  Because
 *       {@code init()} has already been called, the in-memory view is already warm.</li>
 * </ol>
 *
 * <h3>Security</h3>
 * TURN credentials are time-scoped tokens (not permanent secrets) generated by
 * Cloudflare for a 24-hour window.  Storing them in {@link EncryptedSharedPreferences}
 * (AES-256-GCM for values, AES-256-SIV for keys, backed by Android Keystore) provides
 * protection appropriate for short-lived tokens.
 */
public class TurnCredentialCache {

    private static final String TAG    = "TurnCredentialCache";
    private static final long   TTL_MS = 60 * 60 * 1_000L; // 1 hour

    // SharedPreferences keys
    private static final String PREFS_NAME   = "duoshield_turn_cache";
    private static final String KEY_URLS     = "turn_urls";       // pipe-separated
    private static final String KEY_USERNAME = "turn_username";
    private static final String KEY_CRED     = "turn_credential";
    private static final String KEY_FETCHED  = "turn_fetched_at"; // long stored as String

    private static volatile TurnCredentialCache instance;

    // ── In-memory state ───────────────────────────────────────────────────────
    private volatile String[] urls;
    private volatile String   username;
    private volatile String   credential;
    private volatile long     fetchedAtMs = 0L;

    // ── Persistent store (null until init() is called) ────────────────────────
    private SharedPreferences prefs;

    private TurnCredentialCache() {}

    /** Returns the singleton, creating it on first call. */
    public static TurnCredentialCache get() {
        if (instance == null) {
            synchronized (TurnCredentialCache.class) {
                if (instance == null) instance = new TurnCredentialCache();
            }
        }
        return instance;
    }

    /**
     * Initialises the {@link EncryptedSharedPreferences} backing store and loads
     * any credentials previously persisted to disk into the in-memory cache.
     *
     * <p>Safe to call multiple times — idempotent after the first successful call.
     * Should be called from {@code CallActivity.onCreate()} before
     * {@link TurnCredentialFetcher#prefetch}.
     */
    public static synchronized void init(Context context) {
        TurnCredentialCache cache = get();
        if (cache.prefs != null) return; // already initialised
        try {
            MasterKey masterKey = new MasterKey.Builder(context)
                    .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
                    .build();
            cache.prefs = EncryptedSharedPreferences.create(
                    context,
                    PREFS_NAME,
                    masterKey,
                    EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
                    EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM);
            cache.loadFromPrefs();
            Log.d(TAG, "Encrypted TURN credential store initialised"
                    + (cache.isValid() ? " — warm cache loaded from disk" : " — cache cold"));
        } catch (Exception e) {
            // Non-fatal: fall back to in-memory only.  The call still works;
            // it just needs to wait for the async TurnCredentialFetcher fetch.
            Log.w(TAG, "EncryptedSharedPreferences init failed — in-memory only: " + e.getMessage());
        }
    }

    // ── Read / Write ──────────────────────────────────────────────────────────

    public synchronized void set(String[] urls, String username, String credential) {
        this.urls        = urls;
        this.username    = username;
        this.credential  = credential;
        this.fetchedAtMs = System.currentTimeMillis();
        if (prefs != null) saveToPrefs();
    }

    /** Returns true if credentials are present and younger than {@link #TTL_MS}. */
    public synchronized boolean isValid() {
        return urls != null && username != null && credential != null
                && (System.currentTimeMillis() - fetchedAtMs) < TTL_MS;
    }

    public synchronized String[] getUrls()       { return urls; }
    public synchronized String   getUsername()   { return username; }
    public synchronized String   getCredential() { return credential; }

    // ── Persistence helpers ───────────────────────────────────────────────────

    /** Loads credentials from the encrypted prefs into memory. Must be called under lock. */
    private void loadFromPrefs() {
        if (prefs == null) return;
        String rawUrls  = prefs.getString(KEY_URLS, null);
        String user     = prefs.getString(KEY_USERNAME, null);
        String cred     = prefs.getString(KEY_CRED, null);
        String fetchedS = prefs.getString(KEY_FETCHED, "0");
        if (rawUrls == null || user == null || cred == null) return;

        long fetched;
        try { fetched = Long.parseLong(fetchedS); } catch (NumberFormatException e) { return; }

        // Discard if already expired — no point warming the in-memory cache with stale data.
        if ((System.currentTimeMillis() - fetched) >= TTL_MS) {
            Log.d(TAG, "Persisted TURN credentials expired — ignoring");
            return;
        }

        this.urls        = rawUrls.split("\\|");
        this.username    = user;
        this.credential  = cred;
        this.fetchedAtMs = fetched;
    }

    /** Persists the current in-memory state to encrypted prefs. Must be called under lock. */
    private void saveToPrefs() {
        if (prefs == null || urls == null) return;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < urls.length; i++) {
            if (i > 0) sb.append('|');
            sb.append(urls[i]);
        }
        prefs.edit()
             .putString(KEY_URLS,     sb.toString())
             .putString(KEY_USERNAME, username)
             .putString(KEY_CRED,     credential)
             .putString(KEY_FETCHED,  String.valueOf(fetchedAtMs))
             .apply();
    }
}
