// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/duoshield-calls/IncomingCall.tsx": () => import("../components/mockups/duoshield-calls/IncomingCall.tsx"),
  "./components/mockups/duoshield-calls/VideoBanner.tsx": () => import("../components/mockups/duoshield-calls/VideoBanner.tsx"),
  "./components/mockups/duoshield-calls/VideoCall.tsx": () => import("../components/mockups/duoshield-calls/VideoCall.tsx")
};
